// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lambda_max_group_lasso
double lambda_max_group_lasso(arma::colvec& VECTOR_Y, IntegerVector VECTOR_GROUPS, arma::colvec& VECTOR_WEIGHTS_FEATURES, arma::colvec& VECTOR_BETA, arma::mat& MATRIX_X);
RcppExport SEXP _seagull_lambda_max_group_lasso(SEXP VECTOR_YSEXP, SEXP VECTOR_GROUPSSEXP, SEXP VECTOR_WEIGHTS_FEATURESSEXP, SEXP VECTOR_BETASEXP, SEXP MATRIX_XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_Y(VECTOR_YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type VECTOR_GROUPS(VECTOR_GROUPSSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_WEIGHTS_FEATURES(VECTOR_WEIGHTS_FEATURESSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_BETA(VECTOR_BETASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type MATRIX_X(MATRIX_XSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_max_group_lasso(VECTOR_Y, VECTOR_GROUPS, VECTOR_WEIGHTS_FEATURES, VECTOR_BETA, MATRIX_X));
    return rcpp_result_gen;
END_RCPP
}
// lambda_max_lasso
double lambda_max_lasso(arma::colvec& VECTOR_Y, arma::colvec& VECTOR_WEIGHTS_FEATURES, arma::colvec& VECTOR_BETA, arma::mat& MATRIX_X);
RcppExport SEXP _seagull_lambda_max_lasso(SEXP VECTOR_YSEXP, SEXP VECTOR_WEIGHTS_FEATURESSEXP, SEXP VECTOR_BETASEXP, SEXP MATRIX_XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_Y(VECTOR_YSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_WEIGHTS_FEATURES(VECTOR_WEIGHTS_FEATURESSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_BETA(VECTOR_BETASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type MATRIX_X(MATRIX_XSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_max_lasso(VECTOR_Y, VECTOR_WEIGHTS_FEATURES, VECTOR_BETA, MATRIX_X));
    return rcpp_result_gen;
END_RCPP
}
// lambda_max_sparse_group_lasso
double lambda_max_sparse_group_lasso(double ALPHA, arma::colvec& VECTOR_Y, IntegerVector VECTOR_GROUPS, arma::colvec& VECTOR_WEIGHTS_FEATURES, arma::colvec& VECTOR_BETA, arma::mat& MATRIX_X);
RcppExport SEXP _seagull_lambda_max_sparse_group_lasso(SEXP ALPHASEXP, SEXP VECTOR_YSEXP, SEXP VECTOR_GROUPSSEXP, SEXP VECTOR_WEIGHTS_FEATURESSEXP, SEXP VECTOR_BETASEXP, SEXP MATRIX_XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ALPHA(ALPHASEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_Y(VECTOR_YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type VECTOR_GROUPS(VECTOR_GROUPSSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_WEIGHTS_FEATURES(VECTOR_WEIGHTS_FEATURESSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_BETA(VECTOR_BETASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type MATRIX_X(MATRIX_XSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_max_sparse_group_lasso(ALPHA, VECTOR_Y, VECTOR_GROUPS, VECTOR_WEIGHTS_FEATURES, VECTOR_BETA, MATRIX_X));
    return rcpp_result_gen;
END_RCPP
}
// seagull_bisection
double seagull_bisection(int ROWS, double ALPHA, double LEFT_BORDER, double RIGHT_BORDER, double GROUP_WEIGHT, arma::colvec VECTOR_WEIGHTS, arma::colvec& VECTOR_IN);
RcppExport SEXP _seagull_seagull_bisection(SEXP ROWSSEXP, SEXP ALPHASEXP, SEXP LEFT_BORDERSEXP, SEXP RIGHT_BORDERSEXP, SEXP GROUP_WEIGHTSEXP, SEXP VECTOR_WEIGHTSSEXP, SEXP VECTOR_INSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ROWS(ROWSSEXP);
    Rcpp::traits::input_parameter< double >::type ALPHA(ALPHASEXP);
    Rcpp::traits::input_parameter< double >::type LEFT_BORDER(LEFT_BORDERSEXP);
    Rcpp::traits::input_parameter< double >::type RIGHT_BORDER(RIGHT_BORDERSEXP);
    Rcpp::traits::input_parameter< double >::type GROUP_WEIGHT(GROUP_WEIGHTSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type VECTOR_WEIGHTS(VECTOR_WEIGHTSSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type VECTOR_IN(VECTOR_INSEXP);
    rcpp_result_gen = Rcpp::wrap(seagull_bisection(ROWS, ALPHA, LEFT_BORDER, RIGHT_BORDER, GROUP_WEIGHT, VECTOR_WEIGHTS, VECTOR_IN));
    return rcpp_result_gen;
END_RCPP
}
// seagull_group_lasso
List seagull_group_lasso(NumericVector VECTOR_Yc, NumericMatrix MATRIX_Xc, NumericVector VECTOR_WEIGHTS_FEATURESc, IntegerVector VECTOR_GROUPS, NumericVector VECTOR_BETAc, IntegerVector VECTOR_INDEX_PERMUTATION, double EPSILON_CONVERGENCE, int ITERATION_MAX, double GAMMA, double LAMBDA_MAX, double PROPORTION_XI, int NUMBER_INTERVALS, int NUMBER_FIXED_EFFECTS, bool TRACE_PROGRESS);
RcppExport SEXP _seagull_seagull_group_lasso(SEXP VECTOR_YcSEXP, SEXP MATRIX_XcSEXP, SEXP VECTOR_WEIGHTS_FEATUREScSEXP, SEXP VECTOR_GROUPSSEXP, SEXP VECTOR_BETAcSEXP, SEXP VECTOR_INDEX_PERMUTATIONSEXP, SEXP EPSILON_CONVERGENCESEXP, SEXP ITERATION_MAXSEXP, SEXP GAMMASEXP, SEXP LAMBDA_MAXSEXP, SEXP PROPORTION_XISEXP, SEXP NUMBER_INTERVALSSEXP, SEXP NUMBER_FIXED_EFFECTSSEXP, SEXP TRACE_PROGRESSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_Yc(VECTOR_YcSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type MATRIX_Xc(MATRIX_XcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_WEIGHTS_FEATURESc(VECTOR_WEIGHTS_FEATUREScSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type VECTOR_GROUPS(VECTOR_GROUPSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_BETAc(VECTOR_BETAcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type VECTOR_INDEX_PERMUTATION(VECTOR_INDEX_PERMUTATIONSEXP);
    Rcpp::traits::input_parameter< double >::type EPSILON_CONVERGENCE(EPSILON_CONVERGENCESEXP);
    Rcpp::traits::input_parameter< int >::type ITERATION_MAX(ITERATION_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type GAMMA(GAMMASEXP);
    Rcpp::traits::input_parameter< double >::type LAMBDA_MAX(LAMBDA_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type PROPORTION_XI(PROPORTION_XISEXP);
    Rcpp::traits::input_parameter< int >::type NUMBER_INTERVALS(NUMBER_INTERVALSSEXP);
    Rcpp::traits::input_parameter< int >::type NUMBER_FIXED_EFFECTS(NUMBER_FIXED_EFFECTSSEXP);
    Rcpp::traits::input_parameter< bool >::type TRACE_PROGRESS(TRACE_PROGRESSSEXP);
    rcpp_result_gen = Rcpp::wrap(seagull_group_lasso(VECTOR_Yc, MATRIX_Xc, VECTOR_WEIGHTS_FEATURESc, VECTOR_GROUPS, VECTOR_BETAc, VECTOR_INDEX_PERMUTATION, EPSILON_CONVERGENCE, ITERATION_MAX, GAMMA, LAMBDA_MAX, PROPORTION_XI, NUMBER_INTERVALS, NUMBER_FIXED_EFFECTS, TRACE_PROGRESS));
    return rcpp_result_gen;
END_RCPP
}
// seagull_lasso
List seagull_lasso(NumericVector VECTOR_Yc, NumericMatrix MATRIX_Xc, NumericVector VECTOR_WEIGHTS_FEATURESc, NumericVector VECTOR_BETAc, double EPSILON_CONVERGENCE, int ITERATION_MAX, double GAMMA, double LAMBDA_MAX, double PROPORTION_XI, int NUMBER_INTERVALS, int NUMBER_FIXED_EFFECTS, bool TRACE_PROGRESS);
RcppExport SEXP _seagull_seagull_lasso(SEXP VECTOR_YcSEXP, SEXP MATRIX_XcSEXP, SEXP VECTOR_WEIGHTS_FEATUREScSEXP, SEXP VECTOR_BETAcSEXP, SEXP EPSILON_CONVERGENCESEXP, SEXP ITERATION_MAXSEXP, SEXP GAMMASEXP, SEXP LAMBDA_MAXSEXP, SEXP PROPORTION_XISEXP, SEXP NUMBER_INTERVALSSEXP, SEXP NUMBER_FIXED_EFFECTSSEXP, SEXP TRACE_PROGRESSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_Yc(VECTOR_YcSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type MATRIX_Xc(MATRIX_XcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_WEIGHTS_FEATURESc(VECTOR_WEIGHTS_FEATUREScSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_BETAc(VECTOR_BETAcSEXP);
    Rcpp::traits::input_parameter< double >::type EPSILON_CONVERGENCE(EPSILON_CONVERGENCESEXP);
    Rcpp::traits::input_parameter< int >::type ITERATION_MAX(ITERATION_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type GAMMA(GAMMASEXP);
    Rcpp::traits::input_parameter< double >::type LAMBDA_MAX(LAMBDA_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type PROPORTION_XI(PROPORTION_XISEXP);
    Rcpp::traits::input_parameter< int >::type NUMBER_INTERVALS(NUMBER_INTERVALSSEXP);
    Rcpp::traits::input_parameter< int >::type NUMBER_FIXED_EFFECTS(NUMBER_FIXED_EFFECTSSEXP);
    Rcpp::traits::input_parameter< bool >::type TRACE_PROGRESS(TRACE_PROGRESSSEXP);
    rcpp_result_gen = Rcpp::wrap(seagull_lasso(VECTOR_Yc, MATRIX_Xc, VECTOR_WEIGHTS_FEATURESc, VECTOR_BETAc, EPSILON_CONVERGENCE, ITERATION_MAX, GAMMA, LAMBDA_MAX, PROPORTION_XI, NUMBER_INTERVALS, NUMBER_FIXED_EFFECTS, TRACE_PROGRESS));
    return rcpp_result_gen;
END_RCPP
}
// seagull_sparse_group_lasso
List seagull_sparse_group_lasso(NumericVector VECTOR_Yc, NumericMatrix MATRIX_Xc, NumericVector VECTOR_WEIGHTS_FEATURESc, IntegerVector VECTOR_GROUPS, NumericVector VECTOR_BETAc, IntegerVector VECTOR_INDEX_PERMUTATION, double ALPHA, double EPSILON_CONVERGENCE, int ITERATION_MAX, double GAMMA, double LAMBDA_MAX, double PROPORTION_XI, int NUMBER_INTERVALS, int NUMBER_FIXED_EFFECTS, bool TRACE_PROGRESS);
RcppExport SEXP _seagull_seagull_sparse_group_lasso(SEXP VECTOR_YcSEXP, SEXP MATRIX_XcSEXP, SEXP VECTOR_WEIGHTS_FEATUREScSEXP, SEXP VECTOR_GROUPSSEXP, SEXP VECTOR_BETAcSEXP, SEXP VECTOR_INDEX_PERMUTATIONSEXP, SEXP ALPHASEXP, SEXP EPSILON_CONVERGENCESEXP, SEXP ITERATION_MAXSEXP, SEXP GAMMASEXP, SEXP LAMBDA_MAXSEXP, SEXP PROPORTION_XISEXP, SEXP NUMBER_INTERVALSSEXP, SEXP NUMBER_FIXED_EFFECTSSEXP, SEXP TRACE_PROGRESSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_Yc(VECTOR_YcSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type MATRIX_Xc(MATRIX_XcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_WEIGHTS_FEATURESc(VECTOR_WEIGHTS_FEATUREScSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type VECTOR_GROUPS(VECTOR_GROUPSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VECTOR_BETAc(VECTOR_BETAcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type VECTOR_INDEX_PERMUTATION(VECTOR_INDEX_PERMUTATIONSEXP);
    Rcpp::traits::input_parameter< double >::type ALPHA(ALPHASEXP);
    Rcpp::traits::input_parameter< double >::type EPSILON_CONVERGENCE(EPSILON_CONVERGENCESEXP);
    Rcpp::traits::input_parameter< int >::type ITERATION_MAX(ITERATION_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type GAMMA(GAMMASEXP);
    Rcpp::traits::input_parameter< double >::type LAMBDA_MAX(LAMBDA_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type PROPORTION_XI(PROPORTION_XISEXP);
    Rcpp::traits::input_parameter< int >::type NUMBER_INTERVALS(NUMBER_INTERVALSSEXP);
    Rcpp::traits::input_parameter< int >::type NUMBER_FIXED_EFFECTS(NUMBER_FIXED_EFFECTSSEXP);
    Rcpp::traits::input_parameter< bool >::type TRACE_PROGRESS(TRACE_PROGRESSSEXP);
    rcpp_result_gen = Rcpp::wrap(seagull_sparse_group_lasso(VECTOR_Yc, MATRIX_Xc, VECTOR_WEIGHTS_FEATURESc, VECTOR_GROUPS, VECTOR_BETAc, VECTOR_INDEX_PERMUTATION, ALPHA, EPSILON_CONVERGENCE, ITERATION_MAX, GAMMA, LAMBDA_MAX, PROPORTION_XI, NUMBER_INTERVALS, NUMBER_FIXED_EFFECTS, TRACE_PROGRESS));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_seagull_lambda_max_group_lasso", (DL_FUNC) &_seagull_lambda_max_group_lasso, 5},
    {"_seagull_lambda_max_lasso", (DL_FUNC) &_seagull_lambda_max_lasso, 4},
    {"_seagull_lambda_max_sparse_group_lasso", (DL_FUNC) &_seagull_lambda_max_sparse_group_lasso, 6},
    {"_seagull_seagull_bisection", (DL_FUNC) &_seagull_seagull_bisection, 7},
    {"_seagull_seagull_group_lasso", (DL_FUNC) &_seagull_seagull_group_lasso, 14},
    {"_seagull_seagull_lasso", (DL_FUNC) &_seagull_seagull_lasso, 12},
    {"_seagull_seagull_sparse_group_lasso", (DL_FUNC) &_seagull_seagull_sparse_group_lasso, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_seagull(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
